- .devops/deploy-argocd-apps.yml
- .devops/templates/deploy-argo-template.yml
- pipeline now don't run the empty apps category
- pipeline don't use category+app name any more, but only app_name
- minor fix
> fix: Deploy azdo now supports the new category apps

- helm/dev/top/p4pa-auth/values.yaml
> fix: add p4pa-auth dev test postman

- .devops/deploy-argocd-apps.yml
Now azdo pipeline show info about env, argocd branch and postman branch used
> fix: Pipeline name now show better info

- .devops/deploy-argocd-apps.yml
- .devops/templates/deploy-argo-template.yml
Is possible via trigger and manually to choose the target branch for all the applications to test a new configuration in HELM
> feat: Argocd now is possible to choose the target branch 

- helm/dev/top/p4pa-pagopa-payments/values.yaml
- helm/prod/top/p4pa-pagopa-payments/values.yaml
- helm/uat/top/p4pa-pagopa-payments/values.yaml
> fix: P4ADEV-1925 fix wsdl exposure

- helm/_global/p4pa-auth.yaml
> feat: P4ADEV-1931 remove MyPay and MyPivot items from p4pa-auth

- helm/_global/p4pa-workflow-hub.yaml
> fix: Fix workflow hub values

- helm/dev/top/p4pa-pagopa-payments/values.yaml
- helm/prod/top/p4pa-pagopa-payments/values.yaml
- helm/uat/top/p4pa-pagopa-payments/values.yaml
> feat: P4PADEV-1776 set env variables

- helm/_global/p4pa-pu-bff.yaml
> feat: P4ADEV-1939-ingestion-flow-file-list

- helm/dev/top/p4pa-debt-positions/values.yaml
> fix: Logging level set to debug for debt-position

- helm/_global/p4pa-process-executions.yaml
> fix: Values p4pa-process-execution

- .github/terraform/00_data.tf
- .github/terraform/99_locals.tf
- .github/terraform/env/dev/terraform.tfvars
- .github/terraform/env/prod/terraform.tfvars
- .github/terraform/env/uat/backend.tfvars
- .github/terraform/env/uat/terraform.tfvars
- CODEOWNERS
> fix: Terraform init repository

- helm/_global/p4pa-send-notification.yaml
- helm/dev/ext/p4pa-send-notification/values.yaml
- helm/prod/ext/p4pa-send-notification/values.yaml
- helm/uat/ext/p4pa-send-notification/values.yaml
> feat: P4ADEV-1854 edit helm p4pa-send

- helm/dev/top/p4pa-pagopa-payments/values.yaml
- helm/prod/top/p4pa-pagopa-payments/values.yaml
- helm/uat/top/p4pa-pagopa-payments/values.yaml
> feat: P4PADEV-2115 set env variables

- .devops/deploy-argocd-apps.yml
> fix: PAYMCLOUD-242 trigger azure devops

- helm/_global/p4pa-workflow-hub.yaml
- helm/_global/p4pa-workflow-worker.yaml
> fix: Workflow env vars

- helm/dev/top/p4pa-pagopa-payments/values.yaml
- helm/prod/top/p4pa-pagopa-payments/values.yaml
- helm/uat/top/p4pa-pagopa-payments/values.yaml
> fix: ACA base url

- helm/_global/p4pa-pagopa-payments.yaml
> fix: PagopaPayments debt-positions url

- helm/_global/p4pa-pu-bff.yaml
> feat: P4ADEV-2090 Added classification base url to bff yaml

- helm/_global/p4pa-workflow-hub.yaml
> fix: Workflowhub global config update to set entities ms base url

- helm/_global/p4pa-workflow-worker.yaml
> feat: Add-workflow-hub-base-url-to-worker

- .devops/deploy-argocd-apps.yml
- helm/dev/top/p4pa-pu-sil/values.yaml
> fix: Decoupled deploy top, mid, and ext apps

- helm/dev/top/p4pa-pagopa-payments/values.yaml
- helm/prod/top/p4pa-pagopa-payments/values.yaml
- helm/uat/top/p4pa-pagopa-payments/values.yaml
> feat: P4PADEV-2118 set env variables

- helm/_global/p4pa-organization.yaml
> feat: Add organization-encrypt-password

- helm/_global/p4pa-io-notification.yaml
> fix: P4ADEV-2296-delete-queue-kafka-from-io-notification

- helm/_global/p4pa-io-notification.yaml
> feat: P4ADEV-2377-add-base-url-organization-into-io-notification

- helm/_global/p4pa-pdnd-services.yaml
- helm/dev/mid/p4pa-pdnd-services/values.yaml
- helm/prod/mid/p4pa-pdnd-services/values.yaml
- helm/uat/mid/p4pa-pdnd-services/values.yaml
> fix: Setting ANPR configs

- helm/_global/p4pa-pu-sil.yaml
added SEND_NOTIFICATION_BASE_URL to global p4pa-pu-sil
> feat: P4ADEV-2273-added-SEND_NOTIFICATION_BASE_URL

- helm/_global/p4pa-fileshare.yaml
> feat: P4ADEV-2277-added-SEND_NOTIFICATION_BASE_URL

- helm/dev/ext/p4pa-send-notification/values.yaml
- helm/prod/mid/p4pa-fileshare/values.yaml
- helm/uat/ext/p4pa-send-notification/values.yaml
> feat: P4ADEV-2080 add FileshareBaseURL

- helm/_global/p4pa-send-notification.yaml
> feat: P4ADEV-2232 add organization and workflow base url

- helm/_global/p4pa-send-notification.yaml
> feat: P4ADEV-2080 add shared folder

- helm/_global/p4pa-classification.yaml
> feat: P4ADEV-2521 Update global helm for Classification MS

- helm/_global/p4pa-send-notification.yaml
> feat: P4ADEV-2533 add Citizen datasource config

- helm/_global/p4pa-debt-positions.yaml
> chore: P4ADEV-2535 update helm debt-positions

- helm/_global/p4pa-classification.yaml
> feat: P4ADEV-2592 env variable for hash pepper in classification

- helm/_global/p4pa-debt-positions.yaml
disable debt position pii cache
> fix: P4ADEV-2635 disable debt position pii cache

- helm/_global/p4pa-pagopa-payments.yaml
- helm/dev/top/p4pa-pagopa-payments/values.yaml
- helm/prod/top/p4pa-pagopa-payments/values.yaml
- helm/uat/top/p4pa-pagopa-payments/values.yaml
> feat: P4ADEV-2582 add env variable print payment notice

- helm/_global/p4pa-pu-bff.yaml
> feat: P4ADEV-2580 add PAGOPA_PAYMENTS_BASE_URL to global BFF

- helm/dev/top/p4pa-pu-sil/values.yaml
- helm/prod/top/p4pa-pu-sil/values.yaml
- helm/uat/top/p4pa-pu-sil/values.yaml
> feat: P4ADEV-2874-add-SIL_WSDL_BASE_URL-to-dev-environment

- helm/_global/p4pa-pagopa-payments.yaml
> fix: Add send notification baseUrl to payments

- helm/_global/p4pa-pu-bff.yaml
> feat: Added workflow hub base url to bff yaml

- helm/dev/top/p4pa-debt-positions/values.yaml
- helm/prod/top/p4pa-debt-positions/values.yaml
- helm/uat/top/p4pa-debt-positions/values.yaml
> fix: P4ADEV-3033 add var debt-positions

- helm/dev/mid/p4pa-fileshare/values.yaml
- helm/dev/top/p4pa-pu-sil/values.yaml
- helm/prod/top/p4pa-pu-sil/values.yaml
- helm/uat/top/p4pa-pu-sil/values.yaml
> feat: File-share public base url addition

- helm/_global/p4pa-migration.yaml
> feat: P4ADEV-2861 add value for env variable

- helm/_global/p4pa-migration.yaml
> feat: P4ADEV-3023 add value for env variable

- helm/dev/top/p4pa-pu-sil/values.yaml
- helm/prod/top/p4pa-pu-sil/values.yaml
- helm/uat/top/p4pa-pu-sil/values.yaml
add checkout api url on pu-sil module
add checkout api url on pu-sil module
add checkout api url on pu-sil module
> feat: P4ADEV-3080 add checkout api url on pu-sil module

- helm/_global/p4pa-pu-sil.yaml
add needed dependencies (client modules and API)
add needed dependencies (client modules and API)
add needed dependencies (client modules and API)
add needed dependencies (client modules and API)
> feat: P4ADEV-3076 add needed dependencies (client modules and API)

- helm/_global/p4pa-fileshare.yaml
> fix: Add pagopa payments base url on fileshare

- helm/_global/p4pa-pu-sil.yaml
add workflow-hub base url on pu-sil
add workflow-hub base url on pu-sil
add workflow-hub base url on pu-sil
> feat: P4ADEV-3080 add workflow-hub base url on pu-sil

- helm/dev/top/p4pa-pu-sil/values.yaml
- helm/prod/top/p4pa-pu-sil/values.yaml
- helm/uat/top/p4pa-pu-sil/values.yaml
add default callback url for checkout (pu-sil)
add default callback url for checkout (pu-sil)
add default callback url for checkout (pu-sil)
> feat: P4ADEV-3220 add default callback url for checkout (pu-sil)

- helm/_global/p4pa-pu-sil.yaml
> feat: P4ADEV-3424 Classification MS var for pu-sil

- helm/_global/p4pa-organization.yaml
- helm/dev/top/p4pa-organization/values.yaml
- helm/prod/top/p4pa-organization/values.yaml
- helm/uat/top/p4pa-organization/values.yaml
> feat: P4ADEV-3551 Add FEATURE_ORGANIZATION_PIVA_CHECK values to organization application

- helm/_global/p4pa-workflow-hub.yaml
> fix: P4ADEV-3784 add data events kafka variables

- helm/dev/top/p4pa-pu-sil/values.yaml
- helm/prod/top/p4pa-pu-sil/values.yaml
- helm/uat/top/p4pa-pu-sil/values.yaml
update checkout callback urls
update checkout callback urls
update checkout callback urls
> feat: P4ADEV-3249 update checkout callback urls
